### ISSUE TITLE
Type error on Node ?

### ISSUE THREAD

**Issue by Elried** [8INF840-uqac/Devoir1#17]
From node.hpp
```cpp
std::shared_ptr<T> m_id;
```
`m_id` is a pointer (this might be a bad idea as discussed [here](https://github.com/8INF840-uqac/Devoir1/issues/16)).

However from Node.inl
```cpp
template <class T>
void Node<T>::set_id(T& new_id) {
    m_id = new_id;
}
```
We can see that it is set wit a reference. if the project can compile, it is because this function (`set_id`) is never used and therefore not generated by the compiler (as it is a template function).

**Comment by AmarOk1412** [comment]
yeap
