### ISSUE TITLE
Potentiel improvment

### ISSUE THREAD

**Issue by Elried** [8INF840-uqac/Devoir1#7]
In `Card.cpp`, we can see the following code :
```cpp
Card::Card() {
    std::random_device rd;
    std::mt19937 mt(rd());
    std::uniform_int_distribution<unsigned short> dist(0, MAXRAND);
    m_score = dist(mt) % MAXSCORE + 1;
    m_bonus = dist(mt) % MAXBONUS + 1;
    m_color = static_cast<Color>(dist(mt) % 2);
}
```

In this configuration, both the random device and the random engine are constructed every time a `Card` is created. This can induce unnecessary overhead as those element might be slow to construct.

Declaring those variable as `static` could reduce this overhead.

**Comment by AmarOk1412** [comment]
Indeed.
